[bastion]
bastion ansible_host=18.185.59.114 ansible_user=ec2-user

[eks_workers]
worker-1 ansible_host=10.0.3.154 ansible_user=ec2-user
worker-2 ansible_host=10.0.1.129 ansible_user=ec2-user
worker-3 ansible_host=10.0.2.27 ansible_user=ec2-user
